server:
  port: 8889
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.42.122:3306/big_data?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: fly18
#整合mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.company.springbootDemo.entity
#设置日志级别
logging:
  level:
    com.company.springbootDemo: debug
